language: minimal

os:
  - osx
  - linux

before_install:
  - export PATH=$HOME/.deno/bin:$PATH

install:
  - curl -L https://deno.land/x/install/install.py | python

script:
  - deno test.ts --allow-env --allow-write
